### ISSUE TITLE
Consider using `git-paste`

### ISSUE THREAD

**Issue by blueyed** [mattn/gist-vim#149]
There is a nice command line client for handling gists: https://github.com/defunkt/gist

It would be great, if gist-vim could use it. It supports two-factor authentication out of the box, for example.

There's no support for listing gists and other features from gist-vim however.

Probably it's not a good idea.

**Comment by jalcine** [comment]
[**@blueyed**](https://github.com/blueyed) commented on [Mar 15, 2014, 10:59 AM PDT](https://github.com/mattn/gist-vim/issues/149#issue-29497869 "2014-03-15T17:59:10Z - Replied by Github Comment Enhancer"):
> There is a nice command line client for handling gists: [https://github.com/defunkt/gist](https://github.com/defunkt/gist)
> 
> It would be great, if gist-vim could use it. It supports two-factor authentication out of the box, for example.
> 
> There's no support for listing gists and other features from gist-vim however.
> 
> Probably it's not a good idea.

Currently gist-vim supports listing private and public Gists and 2FA. This issue can be closed.
