### ISSUE TITLE
filename or description

### ISSUE THREAD

**Issue by WitzHsiao** [mattn/gist-vim#177]
I noticed that `:Gist -e a.js` only updates its description. is it better updating its filename instead of its description?

**Comment by mattn** [comment]
Do you mean `-s` not `-e` ?

**Comment by WitzHsiao** [comment]
-e

**Comment by mattn** [comment]
Thus, I can't reproduce it.

**Comment by WitzHsiao** [comment]
I have tried a way in curl. My way is deleting the origin file and create a new file with that name and the content in files in json. And it works. Do you think it's better to save/update "filename" instead of "description"?

**Comment by mattn** [comment]
`-e` doesn't update description. `-s` do it.

**Comment by mattn** [comment]
https://gist.github.com/mattn/257ce618e87008fc6969

I did:

1. `$ vim foo.js` and type some
2. `:Gist`
3. `:Gist -s logging`

**Comment by WitzHsiao** [comment]
It doesn't work in my way.
1. `$ vim`
2. `:Gist -l`
3. edit the gist
4. `:Gist -e -s new_name.sh`

It only change the description.

**Comment by spedepekka** [comment]
For me ```:Gist -e "new-filename.txt"``` does only new revision and does not edit the filename. ```:Gist -s "New description"``` works properly.

**Comment by WitzHsiao** [comment]
@spedepekka thanks, but I wanna find a option to update file name.

@mattn what do you think about it?

**Comment by mattn** [comment]
@WitzHsiao it's possible. I'll look into it in later

**Comment by WitzHsiao** [comment]
@mattn thanks, I'm looking forward to it.
