### ISSUE TITLE
Opening Gist unnecessarily closes split buffer

### ISSUE THREAD

**Issue by Kazark** [mattn/gist-vim#179]
I store my [`.gitconfig`](https://gist.github.com/Kazark/18cfc3ce5239c171ca93) as a Gist. I like to use your plugin to update my Gist as my local `~/.gitconfig` changes. However, when I use this particular workflow, opening the Gist unnecessary closes another window:

 1. Open my Git config: `vim ~/.gitconfig`
 2. Make vertical split for viewing the Gist: `:vne`
 3. Open my list of Gists: `:Gist -l`
 4. Hit <kbd>Enter</kbd> to open the one I want

**Expected**: Vim looks like this:

    ________________________________
    |   Gist list   | ~/.gitconfig |
    |   buffer      |              |
    |---------------|              |
    | Gist          |              |
    | .gitconfig    |              |
    ````````````````````````````````
**Instead**: it actually looks like this:
   
    ________________________________
    | Gist list buffer             |
    |                              |
    |------------------------------|
    | Gist .gitconfig              |
    |                              |
    ````````````````````````````````

**Comment by mattn** [comment]
Added `gist_edit_with_buffers`. Please set `let g:gist_edit_with_buffers = 1` in your vimrc

Btw, how about to add `GistID: 18cfc3ce5239c171ca93`? You can do it with:

1. Open your .gitconfig
2. :Gist

**Comment by Kazark** [comment]
Pulled the latest and added `let g:gist_edit_with_buffers = 1` in my Vim configuration, but this didn't solve the issue; I got the same result. Also, good to know about the `GistID` thing. In this case, there are some portions of the file which I don't want to sync, so I want to manually diff it and sync it with Vim. Thanks.

**Comment by mattn** [comment]
Ah, seems typo.

https://github.com/mattn/gist-vim/commit/370d0d32caf1187f581c221b07b6d01c4f5ab105

will fix

**Comment by mattn** [comment]
done.

**Comment by Kazark** [comment]
Cool, thanks!
