### ISSUE TITLE
Gist should set the filetype on uploaded gists

### ISSUE THREAD

**Issue by kballard** [mattn/gist-vim#185]
I just ran `:Gist` from an unnamed buffer with the `swift` filetype and was rather surprised to see the created gist defaulted to Plain Text. It should use the `&filetype` as the file type of the uploaded gist if it has no filename for it. There should also be a flag to override this explicitly.

**Comment by mattn** [comment]
it doesn't work because gist server doesn't handle file extension.

https://gist.github.com/mattn/614b1b9c863c95bf05f9#file-gistfile1-switf

This is a post that i just posted. see the filename but not syntax highlighted.

**Comment by kballard** [comment]
You typo'd the extension. It's "swift", not "switf". And it doesn't work because `:Gist` didn't even set a file extension at all, the file I pasted show up as `gistfile1.txt` (the default if you don't provide a filename).

To clarify: I'm posting from an unnamed scratch buffer for which I've set the `'filetype'` to `swift`. `:Gist` should generate a filename based on the filetype for me and post it as `gistfile1.swift` instead of posting it without a name.

**Comment by mattn** [comment]
Ah, okay. please add below into your vimrc.
```
let g:gist_extmap = { ".swift": "swift" }
```
https://gist.github.com/mattn/94c90ed66771dd55dff2

**Comment by mattn** [comment]
however, I'll add swift into default extmap. so if you will want to new file extension, please do it for new.

**Comment by kballard** [comment]
Can you please document `g:gist_extmap` as well? It's not currently documented, so I didn't know it existed.

**Comment by mattn** [comment]
okay, will do
