### ISSUE TITLE
"Done: $url" message not appearing after posting

### ISSUE THREAD

**Issue by kballard** [mattn/gist-vim#188]
When I post a gist with `:Gist`, it shows the message telling me that it's posting, but it never shows me the `"Done: $url"` message. If I type `:mess` afterwards I can see it, but otherwise it never appears.

After poking at this, it appears that the call to `winrestview(view)` (inside the call to `s:update_GistID`) is causing this problem. More specifically, that call appears to mark the window as needing to be redrawn, which it will be as soon as the command finishes.

I think the right answer here is to invoke `s:update_GistID` prior to echoing the `Done` message.

**Comment by kballard** [comment]
For reference: I'm running MacVim on OS X 10.10.4.

**Comment by mattn** [comment]
how about this 1985efd9844762b830b4141b72ffbf85d57f6322 ?

**Comment by kballard** [comment]
Yep, that works. Thanks!
