### ISSUE TITLE
No matching autocommands for acwrite buffer (multiple files saving)

### ISSUE THREAD

**Issue by lazywei** [mattn/gist-vim#193]
Hi,

I got this when enabling multiple files features. After I open a multiple files gist and edit both files, I got error when saving (or updating it):

```
E676: No matching autocommands for acwrite buffer 
```

However, the `:Gist -b` command is still working, and I can use it to update the Gist.

**Comment by mattn** [comment]
Could you please let me known how to produce it.

**Comment by lazywei** [comment]
1. Create a gist that contains two files
2. In Vim (actually, I'm using NeoVim), `:Gist -l` to list gists
3. Select the gist just created, which will result in two split windows contain each file respectively.
4. Move the cursor into one of the split windows
5. `:w` gives the error
