### ISSUE TITLE
:Gist -a still asks for github account

### ISSUE THREAD

**Issue by Miesco** [mattn/gist-vim#194]
`:Gist -a` gives:

You don't have configured a Github account. Read ':help gist-vim-setup'.

**Comment by cmosguy** [comment]
I am getting this issue with gvim in windows, and I do have ~/.gist-vim file setup.  Is there any solution here for this? @mattn  @Miesco ?

**Comment by mattn** [comment]
ONce remove or backup ~/.gist-vim and try it again.

**Comment by cmosguy** [comment]
Thanks @mattn, i did not have to do that.  For some reason it just magically started working and I do not understand why.  But it works!  Thanks for making this project!
