### ISSUE TITLE
old variable option gist_use_password_in_gitconfig

### ISSUE THREAD

**Issue by kazuminn** [mattn/gist-vim#195]
If there is "let g:gist_use_password_in_gitconfig = 1" in .vimrc ,not work.

**Comment by mattn** [comment]
I'm not sure. basic auth is obsolete in github APIs. I'm going to remove this line if not required.

https://github.com/mattn/gist-vim/blob/52e2d54a038baf548de01c9413a6ebc8860fa111/autoload/gist.vim#L908-L912

**Comment by kazuminn** [comment]
I'm sorry. 

I went doing according to set up, but there was no setup required. 

absolutly, document is old.

I got it.

**Comment by kazuminn** [comment]
Possibly, it may be my mistake.

**Comment by mattn** [comment]
noprob. btw, basic auth still seems to be. https://developer.github.com/v3/#authentication
