### ISSUE TITLE
Even with github account configured I cannot get past warning msg.

### ISSUE THREAD

**Issue by fourq** [mattn/gist-vim#198]
My ~/.gitconfig
https://gist.github.com/fourq/7c4b9e58ca2fe43b8515

the warning msg that I keep getting: https://github.com/mattn/gist-vim/blob/ea7dc962c5c2ac2a1c4adc94d54cac190d713648/autoload/gist.vim#L719 

Is there something wrong in my .gitconfig?

**Comment by mattn** [comment]
what is output of  `git config --get github.user`?

**Comment by fourq** [comment]
I get my github username fourq. 

Rocky Assad
r@cky.email
@fourq

**Comment by mattn** [comment]
Do you install git?

**Comment by fourq** [comment]
yeah, it's installed. Couldn't live without it =)

**Comment by mattn** [comment]
do you set `gist_post_anonymous` ?

```
:echo gist_post_anonymous
```
at least, if git is installed and gist_post_anonymous is not set, the message shouldn't be displayed. I guess.

**Comment by fourq** [comment]
I don't. Here's my gist settings that I've had for a while. https://github.com/fourq/vim-settings/blob/master/.vimrc#L44

**Comment by mattn** [comment]
https://github.com/mattn/gist-vim/blob/ea7dc962c5c2ac2a1c4adc94d54cac190d713648/autoload/gist.vim#L39-L42

what you get with `:echo substitute(system('git config --get github.user'), "\n", '', '')` ?

**Comment by fourq** [comment]
`fourq`

**Comment by mattn** [comment]
Then `g:github_user` should be set.

**Comment by fourq** [comment]
So I commented out the gist settings that I posted earlier and ran `:Gist` again and got this: http://pi.cky.website/image/0s0F1X3a0z1N

**Comment by fourq** [comment]
seems to be working now for some reason. https://gist.github.com/16fa7fc9d528c4e98b26 (private)

**Comment by mattn** [comment]
did you solve the issue? closable?

**Comment by fourq** [comment]
I suppose so. So just to recap. I commented out my .vimrc settings, opened vim, ran `:Gist`, it then prompt me for my GH creds. I uncommented the .vimrc settings and all is still working. /shrugs. thanks

**Comment by pinggit** [comment]
I got the same issue...
:Gist
You have not configured a Github account. Read ':help gist-vim-setup'.

ping@ubuntu47-3:~$ git config --global --list
user.email=songpingemail@gmail.com
user.name=ping
credential.helper=cache --timeout=3600
ping@ubuntu47-3:~$
ping@ubuntu47-3:~$
ping@ubuntu47-3:~$ git config user.name
ping
ping@ubuntu47-3:~$ git config --get github.user
ping@ubuntu47-3:~$

**Comment by mattn** [comment]
As you mentioned as, you need `github.user`
