### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by xavierartot** [mattn/gist-vim#200]
Hi,
I tried Gist -ls
return: bad credential

:Gist
return:
Post failed: Unauthorized

I created ~/gist-vim
and add a token from github

What I did wrong?

thanks

**Comment by mattn** [comment]
What the `~/gist-vim` is it? do you mea `~/.gist-vim` ? And why you created your self?

**Comment by xavierartot** [comment]
##Because it doesn't exist?
##I installed with Vundle:

```
"write a gist file
Plugin 'mattn/webapi-vim'
Plugin 'mattn/gist-vim'
Plugin 'Wildog/airline-weather.vim'
```
And I created a token, but then?

**Comment by mattn** [comment]
please do NOT create it by yourself.

On 12/21/15, Xavier Artot <notifications@github.com> wrote:
> ##Because it doesn't exist?
> ##I installed with Vundle:
>
> ```
> "write a gist file
> Plugin 'mattn/webapi-vim'
> Plugin 'mattn/gist-vim'
> Plugin 'Wildog/airline-weather.vim'
> ```
> And I created a token, but then?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/gist-vim/issues/200#issuecomment-166133101


-- 
- Yasuhiro Matsumoto
