### ISSUE TITLE
Error 'Post failed: Continue' even though Gist was actually published

### ISSUE THREAD

**Issue by sloria** [mattn/gist-vim#205]
On Vim 7.4.1707 with the latest gist-vim (as of this writing), I am getting an error every time I run `:Gist` that reads 

```
Post failed: Continue
```

Consequently, `let g:gist_open_browser_after_post = 1` does not work.

However, the Gists actually get posted successfully.

Any ideas?

**Comment by mkozjak** [comment]
+1

**Comment by mattn** [comment]
are you using gist.vim over http proxy?

**Comment by mkozjak** [comment]
Nope, but something strange happened. I've tried adding a new private gist just now (after restarting neovim) and it worked... It printed the link...

**Comment by balbeko** [comment]
Having same issue
full vim version information available [here](https://gist.github.com/balbeko/a3b39d670a3dca1f2ced1fe4a3d0ab12)

**Comment by mattn** [comment]
Could you please upgrade webapi-vim?

**Comment by mkozjak** [comment]
I already have the latest version and managed to get the error with ':Gist -p' just now.

**Comment by mattn** [comment]
Could you please apply following patch to debug this issue?

```diff
diff --git a/autoload/webapi/http.vim b/autoload/webapi/http.vim
index f7b9eb2..123768e 100644
--- a/autoload/webapi/http.vim
+++ b/autoload/webapi/http.vim
@@ -159,6 +159,7 @@ function! webapi#http#get(url, ...) abort
     throw "require `curl` or `wget` command"
   endif
   if follow != 0
+    let g:debug = res
     while res =~ '^HTTP/1.\d 3' || res =~ '^HTTP/1\.\d 200 Connection established' || res =~ '^HTTP/1\.\d 100 Continue'
       let pos = stridx(res, "\r\n\r\n")
       if pos != -1
```

1. Apply patch above.
2. `Gist -p`
3. `:echo debug`

Note that please don't paste secret contents on here.

**Comment by mkozjak** [comment]
```E121: Undefined variable: debug
E15: Invalid expression: debug```

**Comment by mattn** [comment]
Maybe fixed. Could you please try latest webapi-vim.

**Comment by mkozjak** [comment]
Installed the update. Same issue.

**Comment by mattn** [comment]
try to pu `let g:debug = res` on https://github.com/mattn/webapi-vim/blob/master/autoload/webapi/http.vim#L243

**Comment by scps950707** [comment]
I have same problem yesterday.
Today I remove .gist-vim in my home directory and remove Personal access tokens in github settings
and use gist-vim and type password again to generate new Personal access token
And it works with no problem now.

**Comment by eiginn** [comment]
Here's an example
Gist I made from vim: https://gist.github.com/eiginn/66abf9416e91bf0e8750ebee13f518f4
debug contents: https://gist.github.com/eiginn/82409aacb4fe3f62e5431d76f4182845

**Comment by mattn** [comment]
Today, I updated webapi-vim. could you please try latest?

**Comment by eiginn** [comment]
could be related to vim-plug, i nuke my re cloned the repo in the right place and its working. previously git log only showed last commit about curl workaround and nothing else

**Comment by mkozjak** [comment]
Updated. Worked for the first paste. Then I tried to paste again with Gist -p and it failed with:
```
Updating gist...                                                                                                                                                       
Post failed: Not Found
```

**Comment by mattn** [comment]
I just run `:Gist -p` twice.

https://gist.github.com/mattn/e25be0af84ee34d14a5ad090cffae5fc

https://gist.github.com/mattn/e25be0af84ee34d14a5ad090cffae5fc/revisions

But no errors.

**Comment by enkeyz** [comment]
Same error here with vim.

**Comment by mattn** [comment]
@enkeyz do you use latest gist-vim and webapi-vim?

**Comment by mkozjak** [comment]
@mattn I did PlugUpdate before testing.

**Comment by mattn** [comment]
@mkozjak could you please try https://github.com/mattn/gist-vim/issues/205#issuecomment-214230465 ?

**Comment by enkeyz** [comment]
@mattn Yes, I'm using latest of everything.

**Comment by conrman** [comment]
+1 on this issue as well. NeoVim 0.1.4 using vim-plug.

**Comment by JLoureir0** [comment]
+1, using neovim 0.1.5

The gist gets posted even with the error. However if i select just a small amount of lines and run :'<, '>Gist there is no error and the plugin behaves as expected.

**Comment by mattn** [comment]
I don't reproduce this after I fixed webapi-vim in few days ago.

**Comment by tombeynon** [comment]
Seeing the same thing with NeoVim 0.1.4 using vim-plug (all versions latest). Seems to only occur when posting to Gist, but does happen on both create and updating.

**Comment by mattn** [comment]
This is my gist that I did `:Gist` and `:w` after opening gist from `:Gist -l`.

https://gist.github.com/mattn/a0158a1b46da3a52cb576a6ff99ebffd/revisions

AFAICS, no problem.

**Comment by tombeynon** [comment]
It works fine if I only save a very small gist (e.g. by visual selecting a line and `:'<,'>Gist`, as per @JLoureir0's comment), so your example works fine @mattn. The error seems to appear when you save larger gists - in my case it failed when I tried to save over 20 lines.

**Comment by mkozjak** [comment]
@tombeynon +1

**Comment by mattn** [comment]
This is a gist I just post https://gist.github.com/mattn/318aa07ee9cee4c47984cdb7c27c6d69/revisions

6498 lines.

**Comment by mattn** [comment]
And this is one that `:<,>Gist` of mbyte.c

https://gist.github.com/mattn/dadb18fc63ff457acc89b37878d23553

**Comment by JLoureir0** [comment]
With Vim 7.4.1707 the behavior is exactly the same as NeoVim, it post to Github but it gives out the error unless the amount of data on the gist is really small.

My version of curl is 7.48.0

**Comment by tombeynon** [comment]
I can reproduce in Vim 7.3 using [this minimal vimrc](https://gist.github.com/tombeynon/2fd5d60a8b9c1dc7b113779240bf384f), and [this content](https://gist.github.com/tombeynon/eeae9f690c47f5f72e8fb0fa87f6edc9). 

```
vim -u test-vimrc
```

As mentioned it does actually save (that gist I linked to is the result of getting that error), and doesn't seem to happen with smaller files. 

<img width="912" alt="screen shot 2016-05-11 at 12 17 09" src="https://cloud.githubusercontent.com/assets/670623/15179221/5bc6f0bc-1772-11e6-891e-a1901d87cd62.png">

**Comment by JLoureir0** [comment]
@mattn:
> try to put `let g:debug = res` on https://github.com/mattn/webapi-vim/blob/master/autoload/webapi/http.vim#L243

Here is the `:echo debug` result: https://gist.github.com/JLoureir0/f626c723a61d12b687772519fe3f0864#file-t-txt

**Comment by mattn** [comment]
Succeeded.

https://gist.github.com/fb18979882303f19298749fc06b5bce1

**Comment by mattn** [comment]
Maybe this part doesn't work expected.

https://github.com/mattn/webapi-vim/blob/master/autoload/webapi/http.vim#L243

**Comment by mattn** [comment]
Someone, could you please try following?

1. download [this](https://gist.githubusercontent.com/JLoureir0/f626c723a61d12b687772519fe3f0864/raw/0f4b55d1c7349d7fc4e007277de6d24f3ca100db/t.txt)
2. save [aa.vim](https://gist.github.com/672e97387f2628902e73156ce91c1152) in same directory
3. `:so aa.vim`

**Comment by JLoureir0** [comment]
Output for aa.vim https://gist.github.com/JLoureir0/eff71cbb30c7e827cc23d5dab9c8d90a#file-aa_output

**Comment by mattn** [comment]
Strange. Then your gist-vim or webapi-vim should work well.

**Comment by mattn** [comment]
Many thanks to responses for this.

I figure out that some version of curl return response that contains strange \r.

**Comment by tombeynon** [comment]
Thanks for the getting to the bottom of it @mattn - working great now.

**Comment by mkozjak** [comment]
Working good, thanks!

**Comment by JLoureir0** [comment]
Thanks for the fix @mattn. Working great again.

**Comment by mblarsen** [comment]
Still getting (`:Gist`):

```
Posting it to gist...
Post failed: Not Found
Press ENTER or type command to continue
```
MacVim
Both plugins updated just now
Using token in `~/.gist-vim`

**Comment by mattn** [comment]
@mblarsen did you try with latest gist-vim and webapi-vim ?

**Comment by mblarsen** [comment]
@mattn I ran an update with vundle's :PluginUpdate should I update manually to get the latest?
Note that I can read gists but I cannot post unless anonymous.

**Comment by mblarsen** [comment]
@mattn Just tried checking out both repos. It made no difference. I can post as anonymous only, but I can connect to github and get my gists. I cannot save them after making changes.

**Comment by mblarsen** [comment]
@mattn my apologies, it turns out that my two-factor token didn't have gist access.

**Comment by mattn** [comment]
:)
