### ISSUE TITLE
can't setup the password

### ISSUE THREAD

**Issue by etorth** [mattn/gist-vim#222]
Gist.vim requires authorization to use the GitHub API. These settings are stored in "~/.gist-vim". If you want to revoke, do "rm ~/.gist-vim".
GitHub Password for etorth:**********Error detected while processing function gist#Gist[180]..<SNR>72_GistPost[9]..<SNR>72_GistGetAuthHeader[54]..webapi#json#decode:
line   33:
E15: Invalid expression: 
Press ENTER or type command to continue

**Comment by mattn** [comment]
What version of vim do you use?

**Comment by etorth** [comment]
Thanks, I given up.
Not because of this plugin, just because this company disables git, curl etc...
